### ISSUE TITLE
pyramid and maxfour font is broken ?

### ISSUE THREAD

**Issue by akicho8** [miketierney/artii#5]
$ artii -l | grep max
    maxfour

    $ artii -f maxfour sample
    Something has gone horribly wrong!
    Artii says: undefined method `empty?' for nil:NilClass

    $ artii -l | grep pyramid
    pyramid

    $ artii -f pyramid sample
    Something has gone horribly wrong!
    Artii says: undefined method `empty?' for nil:NilClass

Was able to correctly display fonts other than this

**Comment by chris-roerig** [comment]
Seems to be an issue in `Figlet::Font` or possible corrupt fonts

**Comment by common-nighthawk** [comment]
I believe I identified the cause of this bug.  I submitted a PR to fix the issue.  Better 4 years late than never?
